project:
  type: book
  output-dir: _site

book:
  title: "MASA R"
  navbar:
    pinned: true
    background: primary
    title: "MASA R"
    right:
      - icon: github
        href: https://github.com/aliceccheng/masa-r
        aria-label: GitHub
  page-footer:
    left: "© 2026 University of Surrey"
    right: "Built with Quarto"
  search:
    location: sidebar
  chapters:
  - part: "Welcome"
    chapters:
      - index.qmd
      - text: "Introduction"
        href: Introduction.qmd
