project:
  type: book
  output-dir: _site
  # render:
  #   - index.qmd
  #   - Introduction.qmd
  #   - materials/*

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css

metadata-files:
  - "pages/_chapters.yml"

book:
  title: "MASA R"
  page-navigation: true
  navbar:
    pinned: true
    background: primary
    title: "MASA R"
    right:
      - icon: github
        href: https://github.com/aliceccheng/masa-r
        aria-label: GitHub
  page-footer:
    left: "© 2026 University of Surrey"
    right: "Built with Quarto"
  search:
    location: sidebar
  chapters:
    - part: "Welcome"
      chapters:
        - Overview.qmd
        - Introduction.qmd
