---
title: "Intermediate R"
format:
  html:
    css: styles.css
    theme: default
editor: visual
---

## Overview

This an intermediate course in R, focused on data manipulation and plotting.

Please be aware that this course is in development and the contents of this site are likely to change in the future.

::: {.callout-tip icon="false"}
### [{{< fa regular lightbulb >}}]{style="color: #872046;"}  Learning outcomes

By the end of this course, you should be able to:

- [Manipulate data frames]{style="color: #872046;"} by applying functions from the dplyr package (e.g. sorting, filtering, grouping, summarising), either to create summaries or prepare data for further analysis
- [Create and customise plots]{style="color: #872046;"} using the ggplot2 package
:::

## Target audience

This course is designed for anyone who has learned the basics of R and RStudio and is ready to build on those foundations. It is not aimed at a specific discipline, and the examples and exercises are designed to be broadly applicable across a range of subject areas.

## Prerequisites

You should have a basic working knowledge of R and RStudio, up to the level covered in the *Getting Started with R & RStudio* workshop \[link\].

<a href="https://surreylearn.surrey.ac.uk/d2l/le/lessons/215610/topics/3265989" target="_blank" rel="noopener"> These tutorial videos</a> also cover the pre-requisite material.

## Workshop code & templates

The material in this course lines up with the *Intermediate R & RStudio* workshop delivered by MASA.

Code and examples taken directly from the workshop are shown in green panels like the one below, so you can easily match what you see here to the live workshop materials.

The materials also include additional syntax, examples, and explanations to complement the workshop, and can be used as an extension or self‑study resource.

::: {.panel-tabset .panel-green group="language"}
## R

Workshop code and examples are shown in green panels like this one
:::

**Template code**

Sometimes code is shown in blue panels like the one below. This code cannot be directly copied and run in R, but shows the structure of using a particular function. There are blanks spaces with information on what to fill in there.

::: {.panel-tabset .panel-blue group="language"}
## R

Template code is shown in blue panels like this one
:::

## Exercises

Exercises in these materials are labelled according to their level of difficulty:

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: dplyr-table
| Level | Description |
|---------------------|---------------------------------------------------|
| {{< fa star >}} {{< fa regular star >}} {{< fa regular star >}} | Level 1 exercises are similar to the workshop examples. |
| {{< fa star >}} {{< fa star >}} {{< fa regular star >}} | Level 2 exercises extend the workshop examples, for example by using a different function. |
| {{< fa star >}} {{< fa star >}} {{< fa star >}} | Level 3 exercises go beyond the workshop examples, for example by combining multiple ideas or extending the syntax covered. |

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: {#levels-table}
